### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ai** [alexeyraspopov/picocolors#3]
We need tests to avoid regressions.

Feel free to copy Nano Colors tests (they were written from scratch, I didn’t copy them from anywhere).

**Comment by alexeyraspopov** [comment]
Now that v0.1.0 is out with proper testing against different Node.js version, I'm keeping this issue open to track effort related to covering `NO_COLOR` (and related flags/vars) support.

**Comment by alexeyraspopov** [comment]
Final piece is here: https://github.com/alexeyraspopov/picocolors/commit/9002f13a76175d6cfa489c0f47bd4322e74af34b. I've adopted the test cases from nanocolors to test `isColorSupported` flag. The script takes less than a second so I just put it as a part of `benchmarks` job just because it already uses Node v16.
